eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
        - id: graduations
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/graduations/**
        - id: enrollments
          uri: http://localhost:8096
          predicates:
            - Path=/api/v1/enrollments/**
        - id: class
          uri: http://localhost:8096
          predicates:
            - Path=/api/v1/class/**
        - id: auth
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/auth/**



